export const stories = [
 {id:'changan',name:'长安出发',chapter:13,range:'第十二—十三回',caption:'从一个愿望，到第一步',question:'当别人都在说路途险恶，唐僧为什么只指着自己的心？',intro:'离开长安之后，取经还没有变成四人的旅程。面对僧众对前路的担忧，唐僧用自己的誓愿作答；紧接着，他就遭遇了启程后的第一场危难。',quote:'心生，種種魔生；心滅，種種魔滅。',analysis:'这句话出现在众僧谈论路途困难之后。先看他如何回答“为什么去”，再看随后的遭难，就能注意到：发愿与应对具体危险，是两件不同的事。这里是一种文本阅读角度，不把它当作作者唯一的寓意。',prompt:'把这一回的“立下誓愿”和“身陷虎穴”放在一起读，你对唐僧的第一印象变了吗？',category:'历史地理关联',boundary:'唐长安与今日西安有历史空间关联。现代景点用来理解长安与玄奘文化，不等于小说启程的精确位置。',sources:[['原著第十三回','https://zh.wikisource.org/wiki/西遊記/第013回'],['唐长安城遗址 · 西安市地方志','https://xadfz.xa.gov.cn/xadq/rwxa/1960625284585664514.html']],places:['xuanzang','yanping'],x:17,y:66},
 {id:'nvguo',name:'西梁女国',chapter:54,range:'第五十三—五十四回',caption:'一纸关文，一场挽留',question:'女王提出婚事后，师徒怎样商量离开的办法？',intro:'取经队伍来到西梁女国，求取通关文牒却遇上女王招婚。唐僧要继续西行，悟空则安排脱身的办法。读这一站，可以先放下熟悉的影视印象，看看原文究竟怎样写对话与行动。',quote:'悟空，前面城池相近，市井上人語喧嘩，想是西梁女國。',analysis:'原文的入城提醒、女王的提议和师徒的商议，把这一站推向“怎样离开”的具体问题。人物的言辞有礼数，也有计策；不要只用一段爱情概括全部情节。是否动情属于解读，不能替代文本证据。',prompt:'选一句唐僧的回答，再看他接下来的行动：话语与行动是否表达了同一件事？',category:'多地文化比较',boundary:'泸沽湖的“女儿国”称谓与丹巴的东女国文化，各有地方资料。它们不是“小说原型已经确定”的证据，也不能把现实族群等同于小说中只有女性的国度。',sources:[['原著第五十四回','https://zh.wikisource.org/wiki/西遊記/第054回'],['泸沽湖文化称谓 · 云南省体育局','https://tyj.yn.gov.cn/tyzx/qzty/202311/t20231115_3415397.html'],['丹巴历史文化 · 丹巴县人民政府','https://www.danba.gov.cn/lsyg/article/234317']],places:['lugu','danba'],x:51,y:47},
 {id:'leiyin',name:'小雷音寺',chapter:65,range:'第六十五—六十六回',caption:'看见佛国，还是看见假象',question:'同一座寺院，唐僧与悟空为何作出不同判断？',intro:'眼前有寺院、祥光与佛像，唐僧想要参拜，悟空却察觉异样。师徒进入小雷音寺后落入圈套。这一站把“相信眼前所见”变成了实实在在的险境。',quote:'師父，那去處便是座寺院，卻不知禪光瑞藹之中，又有些凶氣何也。',analysis:'先比较两人分别注意到了什么，再读他们如何回应对方。这里的冲突不仅在于谁判断正确，也在于提醒为什么没有改变行动。这个阅读问题来自人物对话，并不需要替故事寻找一个真实地址。',prompt:'如果只保留两人的对话、暂时不看结局，你会依据哪些线索作判断？',category:'文学场景 · 暂无可靠对应',boundary:'本轮尚无足以建立一对一现实对应的依据。因此不设现实坐标，不提供前往小说寺院的导航。现实中存在同名地点，也不能自动视为原著地点。',sources:[['原著第六十五回','https://zh.wikisource.org/wiki/西遊記/第065回']],places:[],x:82,y:61}
];
export const places = [
 {id:'xuanzang',name:'玄奘广场',region:'西安市',story:'changan',kind:'人物纪念与文化关联',detail:'借玄奘相关纪念空间理解历史人物。不是小说的启程原址。',source:'https://qjxq.xa.gov.cn/zjqj/gyqj/tsqj/5df21c54fd8508098d284dea.html',minutes:45},
 {id:'yanping',name:'唐城墙遗址公园（延平门）',query:'唐城墙遗址公园 延平门',region:'西安市',story:'changan',kind:'历史城市空间',detail:'地方资料将这里介绍为唐长安城延平门段遗址公园，可辅助理解古今城市空间。',source:'https://xdz.xa.gov.cn/zwgk/shgysyjs/wtly/6258df22f8fd1c0bdc8efcdd.html',minutes:60},
 {id:'lugu',name:'泸沽湖',region:'丽江市',story:'nvguo',kind:'文化称谓比较',detail:'当地文旅使用“女儿国”称谓。这是理解相关文化的入口，不是小说原型认定。',source:'https://tyj.yn.gov.cn/tyzx/qzty/202311/t20231115_3415397.html',minutes:120},
 {id:'danba',name:'丹巴县',region:'甘孜藏族自治州',story:'nvguo',kind:'地方历史文化比较',detail:'官方地方资料介绍东女国文化。当前仅为地区研究入口，尚未细化到可打卡的景点。',source:'https://www.danba.gov.cn/lsyg/article/234317',minutes:120,areaOnly:true}
];
export const storyById = id => stories.find(s=>s.id===id) || stories[0];
export const placeById = id => places.find(p=>p.id===id);
